/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as QuotationsNewRouteImport } from './routes/quotations.new'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'
import { Route as QuotationsEditIdRouteImport } from './routes/quotations.edit.$id'
import { Route as InventoryEditIdRouteImport } from './routes/inventory.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsNewRoute = QuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsEditIdRoute = QuotationsEditIdRouteImport.update({
  id: '/quotations/edit/$id',
  path: '/quotations/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryEditIdRoute = InventoryEditIdRouteImport.update({
  id: '/inventory/edit/$id',
  path: '/inventory/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventory/new': typeof InventoryNewRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/inventory/': typeof InventoryIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/quotations/edit/$id': typeof QuotationsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventory/new': typeof InventoryNewRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/inventory': typeof InventoryIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/quotations/edit/$id': typeof QuotationsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventory/new': typeof InventoryNewRoute
  '/quotations/new': typeof QuotationsNewRoute
  '/inventory/': typeof InventoryIndexRoute
  '/inventory/edit/$id': typeof InventoryEditIdRoute
  '/quotations/edit/$id': typeof QuotationsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/inventory/new'
    | '/quotations/new'
    | '/inventory/'
    | '/inventory/edit/$id'
    | '/quotations/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/inventory/new'
    | '/quotations/new'
    | '/inventory'
    | '/inventory/edit/$id'
    | '/quotations/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/inventory/new'
    | '/quotations/new'
    | '/inventory/'
    | '/inventory/edit/$id'
    | '/quotations/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  InventoryNewRoute: typeof InventoryNewRoute
  QuotationsNewRoute: typeof QuotationsNewRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  InventoryEditIdRoute: typeof InventoryEditIdRoute
  QuotationsEditIdRoute: typeof QuotationsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/new': {
      id: '/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof QuotationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations/edit/$id': {
      id: '/quotations/edit/$id'
      path: '/quotations/edit/$id'
      fullPath: '/quotations/edit/$id'
      preLoaderRoute: typeof QuotationsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/edit/$id': {
      id: '/inventory/edit/$id'
      path: '/inventory/edit/$id'
      fullPath: '/inventory/edit/$id'
      preLoaderRoute: typeof InventoryEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  InventoryNewRoute: InventoryNewRoute,
  QuotationsNewRoute: QuotationsNewRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  InventoryEditIdRoute: InventoryEditIdRoute,
  QuotationsEditIdRoute: QuotationsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
